import { createHash } from "node:crypto";
import { isUtf8 } from "node:buffer";
import { posix } from "node:path";
import type { GeneratedMetalPackage } from "../index.js";
import { validateSwiftIdentifier } from "../validation.js";
import { metalGenerationProfile } from "../compatibility.js";

export const metalOutputRecordPath = ".vgpu-native-output.json";

export class MetalOutputRecordError extends Error {
  readonly code = "invalid-output-record";
  constructor(message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = "MetalOutputRecordError";
  }
}

export interface MetalOutputRecord {
  readonly schemaVersion: 1;
  readonly format: typeof metalGenerationProfile.artifactFormat;
  readonly moduleName: string;
  readonly ownerConfiguration: string;
  readonly inputFingerprint: string;
  readonly files: readonly { readonly path: string; readonly sha256: string }[];
}

export interface MetalOutputRecordInput {
  readonly moduleName: string;
  readonly ownerConfiguration: string;
  readonly inputFingerprint: string;
  readonly files: GeneratedMetalPackage["files"];
}

/** Describe generated bytes without writing files or authorizing an output replacement. */
export function createMetalOutputRecord(
  input: MetalOutputRecordInput
): Uint8Array {
  validateSwiftIdentifier(input.moduleName, "moduleName");
  validateIdentity(input.ownerConfiguration, input.inputFingerprint);
  const paths = payloadPaths(input.moduleName);
  if (
    !input.files ||
    typeof input.files !== "object" ||
    Array.isArray(input.files) ||
    Reflect.ownKeys(input.files).length !== paths.length ||
    paths.some(
      (path) =>
        !Object.hasOwn(input.files, path) ||
        !(input.files[path] instanceof Uint8Array) ||
        input.files[path]!.byteLength === 0
    )
  )
    throw new TypeError(
      "Output records require the exact nonempty generated package byte files"
    );
  const record: MetalOutputRecord = {
    schemaVersion: 1,
    format: metalGenerationProfile.artifactFormat,
    moduleName: input.moduleName,
    ownerConfiguration: input.ownerConfiguration,
    inputFingerprint: input.inputFingerprint,
    files: Object.keys(input.files)
      .sort()
      .map((path) => ({
        path,
        sha256: createHash("sha256").update(input.files[path]!).digest("hex"),
      })),
  };
  const bytes = Buffer.from(`${JSON.stringify(record, null, 2)}\n`);
  parseMetalOutputRecord(bytes);
  return bytes;
}

function validateIdentity(
  ownerConfiguration: string,
  inputFingerprint: string
): void {
  if (
    typeof ownerConfiguration !== "string" ||
    !ownerConfiguration.startsWith("../") ||
    ownerConfiguration.endsWith("/") ||
    posix.basename(ownerConfiguration) === ".." ||
    posix.normalize(ownerConfiguration) !== ownerConfiguration ||
    /[\\\u0000-\u001f\u007f\uD800-\uDFFF]/u.test(ownerConfiguration)
  )
    throw new TypeError(
      "Owner configuration must be a canonical relative file path outside the package"
    );
  if (
    typeof inputFingerprint !== "string" ||
    !/^[a-f0-9]{64}$/u.test(inputFingerprint)
  )
    throw new TypeError("Input fingerprint must be a lowercase SHA-256 digest");
}

function payloadPaths(moduleName: string): string[] {
  return [
    "Package.swift",
    `Sources/${moduleName}/Resources/Shaders.metallib`,
    `Sources/${moduleName}/Shaders.generated.swift`,
  ];
}

/** Parse consistency metadata only; this does not inspect or authenticate a directory. */
export function parseMetalOutputRecord(bytes: Uint8Array): MetalOutputRecord {
  try {
    if (
      !(bytes instanceof Uint8Array) ||
      bytes.byteLength > 64 * 1024 ||
      !isUtf8(bytes)
    )
      throw new TypeError("Output record must be valid UTF-8 within 64 KiB");
    return checkedRecord(bytes);
  } catch (cause) {
    throw new MetalOutputRecordError(
      "Output record is malformed or unsupported",
      { cause }
    );
  }
}

function checkedRecord(bytes: Uint8Array): MetalOutputRecord {
  const record = JSON.parse(
    Buffer.from(bytes).toString("utf8")
  ) as MetalOutputRecord;
  exactKeys(record, [
    "schemaVersion",
    "format",
    "moduleName",
    "ownerConfiguration",
    "inputFingerprint",
    "files",
  ]);
  if (
    record.schemaVersion !== 1 ||
    record.format !== metalGenerationProfile.artifactFormat
  )
    throw new TypeError("Unsupported output record format");
  validateSwiftIdentifier(record.moduleName, "moduleName");
  validateIdentity(record.ownerConfiguration, record.inputFingerprint);
  const required = new Set(payloadPaths(record.moduleName));
  if (!Array.isArray(record.files) || record.files.length !== required.size)
    throw new TypeError(
      "Output record must describe the exact generated file set"
    );
  for (const file of record.files) {
    exactKeys(file, ["path", "sha256"]);
    if (
      !required.delete(file.path) ||
      typeof file.sha256 !== "string" ||
      !/^[a-f0-9]{64}$/u.test(file.sha256)
    )
      throw new TypeError(
        "Output record file paths and hashes must match the artifact format"
      );
  }
  return Object.freeze({
    ...record,
    files: Object.freeze(record.files.map((file) => Object.freeze(file))),
  });
}

function exactKeys(value: unknown, keys: readonly string[]): void {
  if (
    value === null ||
    typeof value !== "object" ||
    Array.isArray(value) ||
    Reflect.ownKeys(value).length !== keys.length ||
    keys.some((key) => !Object.hasOwn(value, key))
  )
    throw new TypeError("Output record contains unsupported fields or shape");
}
