export const meta = {
  slug: 'adaptive-quality',
  title: 'Adaptive Quality',
  description:
    'Start on a High pipeline and downgrade once to a cheaper Low pipeline when the GPU tier, battery level, or presented FPS say so. The tier swap is prepared off-screen and every signal is advisory.',
  tags: [
    'performance',
    'adaptive-quality',
    'bloom',
    'post-processing',
    'raymarching',
    'volumetric',
    'animation',
    'shader',
  ],
  capabilities: [
    'webgpu',
    'fragment-shader',
    'render-targets',
    'multi-pass',
    'hdr',
    'adaptive-quality',
    'controls',
    'responsive-canvas',
    'continuous-rendering',
  ],
  thumb: {
    warmupFrames: 30,
    dt: 1 / 60,
    time: 2.5,
  },
  files: [
    'index.tsx',
    'renderer.ts',
    'quality.ts',
    'quality-controller.ts',
    'quality-signals.ts',
    'frame-health.ts',
    'scene.ts',
    'field.wgsl',
    'bloom-extract.wgsl',
    'bloom-blur.wgsl',
    'composite.wgsl',
  ],
} as const;
