// This file is generated by scripts/ingest-examples.mjs. Do not edit by hand.

export interface ExampleThumbPresence {
  readonly card: string;
  readonly hero: string;
}

export const exampleThumbs: Record<string, ExampleThumbPresence> = {
  "adaptive-quality": {
    "card": "/examples/adaptive-quality.card.png",
    "hero": "/examples/adaptive-quality.hero.png"
  },
  "agent-radiance-cascades": {
    "card": "/examples/agent-radiance-cascades.card.png",
    "hero": "/examples/agent-radiance-cascades.hero.png"
  },
  "air-painting": {
    "card": "/examples/air-painting.card.png",
    "hero": "/examples/air-painting.hero.png"
  },
  "anti-aliasing": {
    "card": "/examples/anti-aliasing.card.png",
    "hero": "/examples/anti-aliasing.hero.png"
  },
  "batch-rendering": {
    "card": "/examples/batch-rendering.card.png",
    "hero": "/examples/batch-rendering.hero.png"
  },
  "black-hole": {
    "card": "/examples/black-hole.card.png",
    "hero": "/examples/black-hole.hero.png"
  },
  "clipping": {
    "card": "/examples/clipping.card.png",
    "hero": "/examples/clipping.hero.png"
  },
  "depth-estimation": {
    "card": "/examples/depth-estimation.card.png",
    "hero": "/examples/depth-estimation.hero.png"
  },
  "earth": {
    "card": "/examples/earth.card.png",
    "hero": "/examples/earth.hero.png"
  },
  "environment-map": {
    "card": "/examples/environment-map.card.png",
    "hero": "/examples/environment-map.hero.png"
  },
  "fft-ocean": {
    "card": "/examples/fft-ocean.card.png",
    "hero": "/examples/fft-ocean.hero.png"
  },
  "fft-ocean-surface": {
    "card": "/examples/fft-ocean-surface.card.png",
    "hero": "/examples/fft-ocean-surface.hero.png"
  },
  "fluid": {
    "card": "/examples/fluid.card.png",
    "hero": "/examples/fluid.hero.png"
  },
  "glass-fractal": {
    "card": "/examples/glass-fractal.card.png",
    "hero": "/examples/glass-fractal.hero.png"
  },
  "gradient": {
    "card": "/examples/gradient.card.png",
    "hero": "/examples/gradient.hero.png"
  },
  "instanced-rendering": {
    "card": "/examples/instanced-rendering.card.png",
    "hero": "/examples/instanced-rendering.hero.png"
  },
  "mnist-classifier": {
    "card": "/examples/mnist-classifier.card.png",
    "hero": "/examples/mnist-classifier.hero.png"
  },
  "nextjs-flare": {
    "card": "/examples/nextjs-flare.card.png",
    "hero": "/examples/nextjs-flare.hero.png"
  },
  "optimized-black-hole": {
    "card": "/examples/optimized-black-hole.card.png",
    "hero": "/examples/optimized-black-hole.hero.png"
  },
  "particle-orbit": {
    "card": "/examples/particle-orbit.card.png",
    "hero": "/examples/particle-orbit.hero.png"
  },
  "radiance-cascades": {
    "card": "/examples/radiance-cascades.card.png",
    "hero": "/examples/radiance-cascades.hero.png"
  },
  "raymarched-fractal": {
    "card": "/examples/raymarched-fractal.card.png",
    "hero": "/examples/raymarched-fractal.hero.png"
  },
  "three-tsl": {
    "card": "/examples/three-tsl.card.png",
    "hero": "/examples/three-tsl.hero.png"
  },
  "transmission": {
    "card": "/examples/transmission.card.png",
    "hero": "/examples/transmission.hero.png"
  },
  "triangle-led-front": {
    "card": "/examples/triangle-led-front.card.png",
    "hero": "/examples/triangle-led-front.hero.png"
  },
  "tsl-exports": {
    "card": "/examples/tsl-exports.card.png",
    "hero": "/examples/tsl-exports.hero.png"
  }
};
