export const meta = {
  slug: 'particle-orbit',
  title: 'Particle Orbit',
  description:
    'A shared-device vgpu + TypeGPU experiment: TypeGPU advances light-seeking dust through a radiance field rendered by vgpu, then vgpu draws the same particle buffer zero-copy alongside orbiting lights, HDR bloom, and a CRT finish.',
  tags: [
    'typegpu',
    'instancing',
    'particles',
    'compute',
    'simulation',
    'bloom',
    'lighting',
    'raymarching',
    'post-processing',
    'render-bundles',
    'animation',
  ],
  capabilities: [
    'webgpu',
    'render-targets',
    'multi-pass',
    'instanced-rendering',
    'render-bundles',
    'compute-shader',
    'storage-buffers',
    'gpu-buffer-interop',
    'zero-copy',
    'textures',
    'hdr',
    'pointer-input',
    'responsive-canvas',
    'continuous-rendering',
  ],
  thumb: {
    warmupFrames: 60,
    dt: 1 / 60,
    time: 2,
    requiredLimits: { maxStorageBuffersInVertexStage: 1 },
  },
  files: [
    'index.tsx',
    'renderer.ts',
    'pipeline.ts',
    'dust.ts',
    'radiance.ts',
    'nebula.wgsl',
    'stars.wgsl',
    'atmosphere.wgsl',
    'trails.wgsl',
    'rc-emitter.wgsl',
    'rc-directions.wgsl',
    'sdf-sample.wgsl',
    'jfa-init.wgsl',
    'jfa-pass.wgsl',
    'sdf-finalize.wgsl',
    'radiance-cascade.wgsl',
    'rc-resolve.wgsl',
    'bright.wgsl',
    'blur.wgsl',
    'post.wgsl',
  ],
} as const;
