import { createHash } from "node:crypto";

export const ORIGIN_MAP_CONTRACT = "vgpu-native-origin-map/v1";
export const RESOLVER_HEADER_PREFIX = "// vgsl-module: ";

export class OriginMapError extends Error {
  constructor(code, message) {
    super(`${code}: ${message}`);
    this.name = "OriginMapError";
    this.code = code;
  }
}

/**
 * Builds deliberately coarse provenance for resolveShader() output.
 *
 * A segment says only that the generated bytes belong to an authored module. It
 * does not claim that generated lines or columns still match the authored file:
 * import removal, identifier mangling, declaration DCE, and trim() all make that
 * claim false. Gaps contain resolver-injected headers and separators.
 */
export function buildModuleOriginMap({ wgsl, modules, generatedVirtualPath }) {
  if (typeof wgsl !== "string") {
    throw new OriginMapError("VGPU-C1-ORIGIN-WGSL", "wgsl must be a string");
  }
  if (!Array.isArray(modules) || modules.length === 0) {
    throw new OriginMapError(
      "VGPU-C1-ORIGIN-MODULES",
      "modules must be a non-empty array in resolver emission order"
    );
  }
  if (typeof generatedVirtualPath !== "string" || !generatedVirtualPath) {
    throw new OriginMapError(
      "VGPU-C1-ORIGIN-GENERATED-PATH",
      "generatedVirtualPath must be a non-empty canonical virtual path"
    );
  }

  const expected = modules.map(normalizeModuleRecord);
  const headers = resolverHeaders(wgsl);
  if (headers.length !== expected.length) {
    throw new OriginMapError(
      "VGPU-C1-ORIGIN-HEADER-COUNT",
      `expected ${expected.length} resolver headers, found ${headers.length}`
    );
  }

  for (let index = 0; index < expected.length; index++) {
    const wanted = expected[index];
    const observed = headers[index];
    if (observed.virtualPath !== wanted.virtualPath) {
      throw new OriginMapError(
        "VGPU-C1-ORIGIN-HEADER-ORDER",
        `header ${index} names ${JSON.stringify(
          observed.virtualPath
        )}; expected ${JSON.stringify(wanted.virtualPath)}`
      );
    }
  }

  const segments = [];
  for (let index = 0; index < headers.length; index++) {
    const header = headers[index];
    const nextHeaderStart = headers[index + 1]?.startCharacter ?? wgsl.length;
    const contentEndCharacter = trimGeneratedSeparator(
      wgsl,
      header.contentStartCharacter,
      nextHeaderStart
    );
    if (contentEndCharacter <= header.contentStartCharacter) continue;

    segments.push({
      generated: {
        startByte: utf8Offset(wgsl, header.contentStartCharacter),
        endByte: utf8Offset(wgsl, contentEndCharacter),
      },
      origin: {
        input: expected[index].input,
      },
      precision: "module",
    });
  }

  const sources = [...expected]
    .sort((left, right) => compareCodeUnits(left.input, right.input))
    .map(({ input, sha256 }) => ({ input, sha256 }));

  const map = {
    schemaVersion: 1,
    contractId: ORIGIN_MAP_CONTRACT,
    generatedSource: {
      virtualPath: generatedVirtualPath,
      sha256: sha256Utf8(wgsl),
    },
    sources,
    segments,
  };
  assertValidModuleOriginMap(map, Buffer.byteLength(wgsl, "utf8"));
  return map;
}

export function assertValidModuleOriginMap(map, generatedByteLength) {
  if (
    !map ||
    map.schemaVersion !== 1 ||
    map.contractId !== ORIGIN_MAP_CONTRACT ||
    !Array.isArray(map.sources) ||
    map.sources.length === 0 ||
    !Array.isArray(map.segments) ||
    !Number.isSafeInteger(generatedByteLength) ||
    generatedByteLength < 0
  ) {
    throw new OriginMapError(
      "VGPU-C1-ORIGIN-SHAPE",
      "origin map does not implement the module-origin v1 contract"
    );
  }

  const inputs = new Set();
  for (const [index, source] of map.sources.entries()) {
    if (
      typeof source?.input !== "string" ||
      source.input.length === 0 ||
      inputs.has(source.input) ||
      !/^[a-f0-9]{64}$/u.test(source.sha256 ?? "")
    ) {
      throw new OriginMapError(
        "VGPU-C1-ORIGIN-SOURCE",
        `source ${index} is invalid or duplicates an input identity`
      );
    }
    inputs.add(source.input);
  }

  let previousEnd = 0;
  for (const [index, segment] of map.segments.entries()) {
    const start = segment?.generated?.startByte;
    const end = segment?.generated?.endByte;
    if (
      !Number.isSafeInteger(start) ||
      !Number.isSafeInteger(end) ||
      start < previousEnd ||
      end <= start ||
      end > generatedByteLength
    ) {
      throw new OriginMapError(
        "VGPU-C1-ORIGIN-RANGE",
        `segment ${index} has an invalid or overlapping UTF-8 byte range`
      );
    }
    if (
      segment.precision !== "module" ||
      typeof segment.origin?.input !== "string" ||
      !inputs.has(segment.origin.input) ||
      Object.keys(segment.origin).length !== 1
    ) {
      throw new OriginMapError(
        "VGPU-C1-ORIGIN-SEGMENT",
        `segment ${index} overstates or omits its module-level provenance`
      );
    }
    previousEnd = end;
  }
}

function normalizeModuleRecord(module, index) {
  const virtualPath = module?.virtualPath ?? module?.path;
  const input = module?.input ?? module?.id;
  const sha256 = module?.sha256;
  if (typeof virtualPath !== "string" || !virtualPath) {
    throw new OriginMapError(
      "VGPU-C1-ORIGIN-MODULE-PATH",
      `module ${index} has no virtual path`
    );
  }
  if (typeof input !== "string" || !input) {
    throw new OriginMapError(
      "VGPU-C1-ORIGIN-MODULE-INPUT",
      `module ${JSON.stringify(virtualPath)} has no input identity`
    );
  }
  if (typeof sha256 !== "string" || !/^[a-f0-9]{64}$/u.test(sha256)) {
    throw new OriginMapError(
      "VGPU-C1-ORIGIN-MODULE-HASH",
      `module ${JSON.stringify(virtualPath)} has no lowercase SHA-256`
    );
  }
  return { virtualPath, input, sha256 };
}

function resolverHeaders(wgsl) {
  const expression = /^\/\/ vgsl-module: ([^\r\n]+)\r?$/gmu;
  const headers = [];
  for (const match of wgsl.matchAll(expression)) {
    const startCharacter = match.index;
    const lineEndCharacter = startCharacter + match[0].length;
    const contentStartCharacter =
      wgsl[lineEndCharacter] === "\n" ? lineEndCharacter + 1 : lineEndCharacter;
    headers.push({
      virtualPath: match[1],
      startCharacter,
      contentStartCharacter,
    });
  }
  return headers;
}

/** Resolver emission trims each module before appending its own separators. */
function trimGeneratedSeparator(text, start, end) {
  while (end > start && /\s/u.test(text[end - 1])) end--;
  return end;
}

function utf8Offset(text, characterOffset) {
  return Buffer.byteLength(text.slice(0, characterOffset), "utf8");
}

function sha256Utf8(text) {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

function compareCodeUnits(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}
