export const meta = {
  slug: "three-tsl",
  title: "Lava material",
  description:
    "Author a procedural lava material as plain WGSL modules and wire them into a three.js node material — twelve surface slots, all driven from shader source.",
  tags: ["three", "3d", "shader", "lighting", "hdr"],
  guide: "/docs/guides/threejs",
  capabilities: [
    "webgpu",
    "pointer-orbit",
    "select-control",
    "continuous-rendering",
    "responsive-canvas",
    "multi-pass",
    "hdr",
    "textures",
  ],
  thumb: { warmupFrames: 3, dt: 1 / 60, time: 2.1 },
  files: [
    "index.tsx",
    "renderer.ts",
    "object-drag-controls.ts",
    "scenes.ts",
    "lava-material.ts",
    "bake-lava.ts",
    "environment.ts",
    "lava.wgsl",
    "noise.wgsl",
  ],
} as const;
